
import { serve } from 'https://deno.land/std@0.168.0/http/server.ts'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    console.log('=== ANALYZE CITATIONS FUNCTION INVOKED ===')
    console.log('Request method:', req.method)
    console.log('Request headers:', Object.fromEntries(req.headers.entries()))
    
    const requestBody = await req.json()
    const { documentContent, prompt, documentName } = requestBody

    console.log('Request body keys:', Object.keys(requestBody))
    console.log('Processing citation analysis for:', documentName)
    console.log('Document content length:', documentContent?.length || 0)
    console.log('Prompt length:', prompt?.length || 0)

    if (!documentContent) {
      console.error('Missing document content')
      throw new Error('Document content is required')
    }

    if (!prompt) {
      console.error('Missing analysis prompt')
      throw new Error('Analysis prompt is required')
    }

    // Get OpenAI API key
    const openaiKey = Deno.env.get('OPENAI_API_KEY')
    if (!openaiKey) {
      console.error('OpenAI API key not found in environment')
      throw new Error('OpenAI API key not configured')
    }

    console.log('OpenAI API key found, calling GPT-4.1...')

    // Call GPT-4.1 with document and prompt
    const openaiResponse = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-2025-04-14',
        messages: [
          { role: 'system', content: prompt },
          { role: 'user', content: documentContent }
        ],
        max_tokens: 8000,
        temperature: 0.1
      }),
    })

    console.log('OpenAI response status:', openaiResponse.status)
    
    if (!openaiResponse.ok) {
      const errorText = await openaiResponse.text()
      console.error('OpenAI API error response:', errorText)
      throw new Error(`OpenAI API error: ${openaiResponse.status} - ${errorText}`)
    }

    const openaiData = await openaiResponse.json()
    console.log('OpenAI response received, choices length:', openaiData.choices?.length || 0)
    
    if (!openaiData.choices || openaiData.choices.length === 0) {
      console.error('No choices in OpenAI response:', openaiData)
      throw new Error('No response generated by OpenAI')
    }

    const analysisResult = openaiData.choices[0].message.content
    console.log('Analysis result length:', analysisResult?.length || 0)
    console.log('Analysis result preview (first 200 chars):', analysisResult?.substring(0, 200))

    // Try to parse as JSON, but return raw text if parsing fails
    let parsedResult
    try {
      parsedResult = JSON.parse(analysisResult)
      console.log('Successfully parsed result as JSON')
    } catch (parseError) {
      console.warn('Could not parse result as JSON:', parseError.message)
      console.warn('Raw result will be returned as string')
      parsedResult = analysisResult
    }

    const result = {
      documentName,
      rawResponse: analysisResult,
      parsedData: parsedResult,
      success: true
    }

    console.log('Returning successful result')
    console.log('=== ANALYZE CITATIONS FUNCTION COMPLETED ===')

    return new Response(
      JSON.stringify(result),
      {
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )
  } catch (error) {
    console.error('=== CITATION ANALYSIS ERROR ===')
    console.error('Error message:', error.message)
    console.error('Error stack:', error.stack)
    console.error('Error type:', typeof error)
    
    return new Response(
      JSON.stringify({ 
        error: error.message || 'Unknown error occurred',
        success: false
      }),
      {
        status: 500,
        headers: { ...corsHeaders, 'Content-Type': 'application/json' },
      }
    )
  }
})
