// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wnxehbryldbdeixuljmc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndueGVoYnJ5bGRiZGVpeHVsam1jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5NDM1NjYsImV4cCI6MjA2NTUxOTU2Nn0.j6vGEe3PnKQwytjHac8zACTw1HmVj8PYi5PLoW_Ue3g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);